### ISSUE TITLE
Dont show anything

### ISSUE THREAD

**Issue by damag3** [hayseedbyte/MMM-Helium-Wallet#1]
Hi, Thanks for the module but unfortunately for me it is not working nor the module title appears. What can I do or what could be causing the problem?!

Thank You

**Comment by hayseedbyte** [comment]
Can you post your module config file?

**Comment by damag3** [comment]
Thanks for fast reply

             //DHT11

  {
            module: "MMM-LocalTemperature",
            position: "bottom-right", // Only add a position if you want this module to display the data
            header: "Room Temperature",
            config: {
                sensorPin: 22, // For GPIO 22
				useSudo: true,
				sendTemperature: true,
               
            }
        },

**Comment by hayseedbyte** [comment]
You need something like this:

` 
var config = {

   modules: [

    {

      module: 'MMM-Helium-Wallet',

      position: 'bottom_right'

      config: {

        // See below for configurable options

        address: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

        currency: 'usd'

      },
    },
  ],
};`

**Comment by damag3** [comment]
> You need something like this:
> 
> `var config = { modules: [ { module: 'MMM-Helium-Wallet', position: 'bottom_right' config: { // See below for configurable options address: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' currency: 'usd' }, }, ], };`

Sorry, im with problem with DHT11 modulo too and as I was trying to solve this module, I changed the config to send

**Comment by damag3** [comment]
thats my config

**Comment by damag3** [comment]
I think it's time to take a break, I'm just doing nonsense.
   
   
   Thats my config
   
   
     //Helium
		 
		  {
      module: 'MMM-Helium-Wallet',
      position: 'bottom_right',
      config: {
        address: 'XXXXXXXXXXXXXXXXXXh',
        currency: 'eur',
      }
    },

**Comment by hayseedbyte** [comment]
Ok. I'll do some testing.

**Comment by hayseedbyte** [comment]
Would you mind sanitizing and posting your whole config file?

**Comment by damag3** [comment]
`/* MagicMirror² Config Sample
 *
 * By Michael Teeuw https://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information on how you can configure this file
 * see https://docs.magicmirror.builders/configuration/introduction.html
 * and https://docs.magicmirror.builders/modules/configuration.html
 */
let config = {
	address: "0.0.0.0", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out or empty, is "localhost"
	port: 8080, 
                  ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1", "192.168.1.69"],
                                                               // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false, 		// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "", 	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "", 	// HTTPS Certificate path, only require when useHttps is true

	language: "pt",
	locale: "pt-PT",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
	// local for armv6l processors, default
	//   starts serveronly and then starts chrome browser
	// false, default for all NON-armv6l devices
	// true, force serveronly mode, because you want to.. no UI on this device
modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			
			module: "calendar",
			header: "Feriados",
			position: "top_left",
			config: {
                        calendars: [
		{
			symbol: "calendar-check-o ",
			url: "webcal://calendarr.com/portugal/ics/"
		},
			{
			symbol: "calendar-check-o ",
			url: "https://calendar.google.com/calendar/htmlembed?src=xxxxxxxxxxxxxxxxxxxxxxxxxxx=Europe%2FLondon",		
		},
	]
		}
                   },
		
		
		
		      //Modulos de terceiros


                      //Metereologia
              
 {
   module: 'MMM-NOAA3',
position: 'top_right',
   config: {
       provider: "openweather", // From list above
       apiKey: "xxxxxxxxxxxxxxxx",        // From one of the providers listed above
       airKey: "xxxxxxxxxxxxxxxxxxxx",    
       css: "NOAA3",                   // THIS MUST CONTAIN A CSS STYLE NAME 
   userlat: "38.9xxxxxxx", //MUST HAVE BOTH
       userlon: "-9.4xxxxxxx"  //MUST HAVE BOTH
}
    },

		
		
		 //Pir Sensor

	{
		module: "MMM-PIR-Sensor-Lite",
		position: "top_right",
		config: {
	    sensorPin: 23, // GPIO pin
		rotation: "left",
		showCountDown: false, 
		deactivateDelay: 3 * 60 * 100,
		}
	},
	
	     //Helium
		 
		  {
      module: 'MMM-Helium-Wallet',
      position: 'bottom_right',
      config: {
        address: 'xxxxxxxxxxxxxxxxxxxxxxxxx',
        currency: 'eur',
      }
    },
	
	     //Moon Phase

  {
			module: "MMM-MoonPhase",
			position: "lower_third",
			config: {
				updateInterval: 43200000,
				hemisphere: "N",
				resolution: "detailed",
				basicColor: "white",
				title: false,
				phase: true,
				x: 200,
				y: 200,
				alpha: 0.7
			}
		},	
		
		 //Marine Weather

{
		module: "MMM-MarineWeather",
		position: "top_right",
		config:{
			latitude: 38.xxxx2, // Latitude 
			longitude: -9.xxxx0, // Longitude
			appid: "xxxx-xxxx-xxxx" // StormGlass API key (docs.stormglass.io)
		}
	},
	
	  //Now play Spotify

{
  module: "MMM-NowPlayingOnSpotify",
  position: "top_left",

  config: {
    clientID: "xxxxxxxxxxxxxxxx",
    clientSecret: "xxxxxxxxxxxxxxxxxx",
    accessToken: "xxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
},

       //xiaomi vacuum cleanner
	   
	   {
      module: 'MMM-XiaomiVacuum',
      position: '',
      header: 'Xiaomi Vacuum', // Optional
      config: {
          token: 'xxxxxxxxxxxxxxxxxxxxf',
          ipAddress: '192.168.1.78'
      }
  },   
        
                //DHT11

  {
            module: "MMM-LocalTemperature",
            position: "bottom-right", // Only add a position if you want this module to display the data
            header: "Room Temperature",
            config: {
                sensorPin: 22, // For GPIO 22
				useSudo: true,
				sendTemperature: true,
               
            }
        },   

	{
    module: 'MMM-WS281X-Server',
    config: {
        hostname: '192.168.1.73',
        port: 9999,
        ledOnStart: true,
        ledOnStartEffect: 'start',
        showAlert: true,
        showAlertEffect: 'alert',
        useMMMFaceRecoDNN: false,
        userLoginEffect: 'login',
        userLogoutEffect: 'logout',
        channel: 1,
        led_count: 60,
        led_type: "ws281X",
        invert: 0,
        global_brightness: 255,
        gpionum: 12,
        spi: true,
        spi_dev: '/dev/spidev0.0',
        spi_speed: 20,
        alt_spi_pin: 12
    }
},
	
 
		
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
`

**Comment by hayseedbyte** [comment]
And you did download the folder and put it in your modules folder?

**Comment by hayseedbyte** [comment]
I think I see the problem. I named the repo with all lowercase but the config looks for a folder with capitals. Try renaming the folder to MMM-Helium-Wallet instead of mmm-helium-wallet.

My fault. Still a novice at this sort of thing.

**Comment by damag3** [comment]
Yes, im a noob but not so big. Im using the MagicMirror more than a year, but I always like to introduce new modules.

<img width="508" alt="Captura de ecrã 2022-10-14 133815" src="https://user-images.githubusercontent.com/3237236/195850403-dc497584-843e-445e-b4b7-651bf48748f0.png">


I changed the name of the module to capital letter and now I have a black screen

**Comment by damag3** [comment]
I have now changed it to lowercase in the config. and the name of the folder. The screen already appears but the MMM-Helium-Wallet module still does not appear

**Comment by hayseedbyte** [comment]
can you open the dev console and see if there are any errors?

npm start dev

**Comment by hayseedbyte** [comment]
Please change the name of the folder mmm-helium-wallet to MMM-Helium Wallet. and the config block to module: MMM-Helium-Wallet.

**Comment by damag3** [comment]
I re-installed the module again and saw that you changed the name to uppercase but it gives me a black screen



> [14.10.2022 14:17.28.277] [LOG]   Connecting socket for: MMM-Helium-Wallet
[14.10.2022 14:17.28.279] [LOG]   Starting module helper: MMM-Helium-Wallet
[14.10.2022 14:17.28.280] [LOG]   Sockets connected & modules started ...
[14.10.2022 14:17.28.295] [ERROR] Whoops! There was an uncaught exception...
[14.10.2022 14:17.28.306] [ERROR] Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at doListen (node:net:1559:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8080
}
[14.10.2022 14:17.28.310] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[14.10.2022 14:17.28.311] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[14.10.2022 14:17.28.703] [LOG]   Launching application.
[2983:1014/141729.589077:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[3022:1014/141729.751310:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
[2994:1014/141729.818453:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.

**Comment by damag3** [comment]
> Please change the name of the folder mmm-helium-wallet to MMM-Helium Wallet. and the config block to module: MMM-Helium-Wallet.

I was testing, I changed all the files and nothing, but in capitals on the screen, black. As mentioned above even with new installation

**Comment by hayseedbyte** [comment]
Oh..change the port to 8090 in the config file. Something else is using 8080

**Comment by damag3** [comment]
> Oh..change the port to 8090 in the config file. Something else is using 8080

Regardless of the port, it always gives the same error, and sometimes it's the spotify module, but it still works. Even changing IP to localhost. If i leave the name in uppercase, the screen is black but if i change it to lowercase, I already have the normal screen but the MMM-Helium module shows "loading"

**Comment by hayseedbyte** [comment]
Ok. I've replicated it. Let me compare the code in the repo to the code
running on my MagicMirror

**Comment by hayseedbyte** [comment]
Ok. I think I've fixed it. I've updated the repo if you want to download it and try again.

**Comment by damag3** [comment]
> Ok. I think I've fixed it. I've updated the repo if you want to download it and try again.


Sorry for the late reply but I was out. Now it works perfect. A big thank you for your time

**Comment by hayseedbyte** [comment]
No problem. Thanks for pointing out the issue.
